package com.naposystems.pepito.utility.emojiManager.categories

import com.naposystems.pepito.model.emojiKeyboard.Emoji
import com.naposystems.pepito.model.emojiKeyboard.EmojiCategory

class ActivityCategory : EmojiCategory() {

    init {
        this.id = 4
        this.name = "Activity"
        this.emojiList = arrayListOf(
            Emoji(id = 1, name = "Person in Suit Levitating", code = 0x1F574),
            Emoji(id = 2, name = "Person Climbing", code = 0x1F9D7),
            Emoji(id = 3, name = "Man Climbing", code = 0x1F9D7),
            Emoji(id = 4, name = "Woman Climbing", code = 0x1F9D7),
            Emoji(id = 5, name = "Horse Racing", code = 0x1F3C7),
            Emoji(id = 6, name = "Skier", code = 0x26F7),
            Emoji(id = 7, name = "Snowboarder", code = 0x1F3C2),
            Emoji(id = 8, name = "Person Golfing", code = 0x1F3CC),
            Emoji(id = 9, name = "Man Golfing", code = 0x1F3CC),
            Emoji(id = 10, name = "Woman Golfing", code = 0x1F3CC),
            Emoji(id = 11, name = "Person Surfing", code = 0x1F3C4),
            Emoji(id = 12, name = "Man Surfing", code = 0x1F3C4),
            Emoji(id = 13, name = "Woman Surfing", code = 0x1F3C4),
            Emoji(id = 14, name = "Person Rowing Boat", code = 0x1F6A3),
            Emoji(id = 15, name = "Man Rowing Boat", code = 0x1F6A3),
            Emoji(id = 16, name = "Woman Rowing Boat", code = 0x1F6A3),
            Emoji(id = 17, name = "Person Swimming", code = 0x1F3CA),
            Emoji(id = 18, name = "Man Swimming", code = 0x1F3CA),
            Emoji(id = 19, name = "Woman Swimming", code = 0x1F3CA),
            Emoji(id = 20, name = "Person Bouncing Ball", code = 0x26F9),
            Emoji(id = 21, name = "Man Bouncing Ball", code = 0x26F9),
            Emoji(id = 22, name = "Woman Bouncing Ball", code = 0x26F9),
            Emoji(id = 23, name = "Person Lifting Weights", code = 0x1F3CB),
            Emoji(id = 24, name = "Man Lifting Weights", code = 0x1F3CB),
            Emoji(id = 25, name = "Woman Lifting Weights", code = 0x1F3CB),
            Emoji(id = 26, name = "Person Biking", code = 0x1F6B4),
            Emoji(id = 27, name = "Man Biking", code = 0x1F6B4),
            Emoji(id = 28, name = "Woman Biking", code = 0x1F6B4),
            Emoji(id = 29, name = "Person Mountain Biking", code = 0x1F6B5),
            Emoji(id = 30, name = "Man Mountain Biking", code = 0x1F6B5),
            Emoji(id = 31, name = "Woman Mountain Biking", code = 0x1F6B5),
            Emoji(id = 32, name = "Person Cartwheeling", code = 0x1F938),
            Emoji(id = 33, name = "Man Cartwheeling", code = 0x1F938),
            Emoji(id = 34, name = "Woman Cartwheeling", code = 0x1F938),
            Emoji(id = 35, name = "People Wrestling", code = 0x1F93C),
            Emoji(id = 36, name = "Men Wrestling", code = 0x1F93C),
            Emoji(id = 37, name = "Women Wrestling", code = 0x1F93C),
            Emoji(id = 38, name = "Person Playing Water Polo", code = 0x1F93D),
            Emoji(id = 39, name = "Man Playing Water Polo", code = 0x1F93D),
            Emoji(id = 40, name = "Woman Playing Water Polo", code = 0x1F93D),
            Emoji(id = 41, name = "Person Playing Handball", code = 0x1F93E),
            Emoji(id = 42, name = "Man Playing Handball", code = 0x1F93E),
            Emoji(id = 43, name = "Woman Playing Handball", code = 0x1F93E),
            Emoji(id = 44, name = "Person Juggling", code = 0x1F939),
            Emoji(id = 45, name = "Man Juggling", code = 0x1F939),
            Emoji(id = 46, name = "Woman Juggling", code = 0x1F939),
            Emoji(id = 47, name = "Person in Lotus Position", code = 0x1F9D8),
            Emoji(id = 48, name = "Man in Lotus Position", code = 0x1F9D8),
            Emoji(id = 49, name = "Woman in Lotus Position", code = 0x1F9D8),
            Emoji(id = 50, name = "Circus Tent", code = 0x1F3AA),
            Emoji(id = 51, name = "Skateboard", code = 0x1F6F9),
            Emoji(id = 52, name = "Reminder Ribbon", code = 0x1F397),
            Emoji(id = 53, name = "Admission Tickets", code = 0x1F39F),
            Emoji(id = 54, name = "Ticket", code = 0x1F3AB),
            Emoji(id = 55, name = "Military Medal", code = 0x1F396),
            Emoji(id = 56, name = "Trophy", code = 0x1F3C6),
            Emoji(id = 57, name = "Sports Medal", code = 0x1F3C5),
            Emoji(id = 58, name = "1st Place Medal", code = 0x1F947),
            Emoji(id = 59, name = "2nd Place Medal", code = 0x1F948),
            Emoji(id = 60, name = "3rd Place Medal", code = 0x1F949),
            Emoji(id = 61, name = "Soccer Ball", code = 0x26BD),
            Emoji(id = 62, name = "Baseball", code = 0x26BE),
            Emoji(id = 63, name = "Softball", code = 0x1F94E),
            Emoji(id = 64, name = "Basketball", code = 0x1F3C0),
            Emoji(id = 65, name = "Volleyball", code = 0x1F3D0),
            Emoji(id = 66, name = "American Football", code = 0x1F3C8),
            Emoji(id = 67, name = "Rugby Football", code = 0x1F3C9),
            Emoji(id = 68, name = "Tennis", code = 0x1F3BE),
            Emoji(id = 69, name = "Flying Disc", code = 0x1F94F),
            Emoji(id = 70, name = "Bowling", code = 0x1F3B3),
            Emoji(id = 71, name = "Cricket Game", code = 0x1F3CF),
            Emoji(id = 72, name = "Field Hockey", code = 0x1F3D1),
            Emoji(id = 73, name = "Ice Hockey", code = 0x1F3D2),
            Emoji(id = 74, name = "Lacrosse", code = 0x1F94D),
            Emoji(id = 75, name = "Ping Pong", code = 0x1F3D3),
            Emoji(id = 76, name = "Badminton", code = 0x1F3F8),
            Emoji(id = 77, name = "Boxing Glove", code = 0x1F94A),
            Emoji(id = 78, name = "Martial Arts Uniform", code = 0x1F94B),
            Emoji(id = 79, name = "Flag in Hole", code = 0x26F3),
            Emoji(id = 80, name = "Ice Skate", code = 0x26F8),
            Emoji(id = 81, name = "Fishing Pole", code = 0x1F3A3),
            Emoji(id = 82, name = "Running Shirt", code = 0x1F3BD),
            Emoji(id = 83, name = "Skis", code = 0x1F3BF),
            Emoji(id = 84, name = "Sled", code = 0x1F6F7),
            Emoji(id = 85, name = "Curling Stone", code = 0x1F94C),
            Emoji(id = 86, name = "Direct Hit", code = 0x1F3AF),
            Emoji(id = 87, name = "Pool 8 Ball", code = 0x1F3B1),
            Emoji(id = 88, name = "Video Game", code = 0x1F3AE),
            Emoji(id = 89, name = "Slot Machine", code = 0x1F3B0),
            Emoji(id = 90, name = "Game Die", code = 0x1F3B2),
            Emoji(id = 91, name = "Puzzle Piece", code = 0x1F9E9),
            Emoji(id = 92, name = "Chess Pawn", code = 0x265F),
            Emoji(id = 93, name = "Performing Arts", code = 0x1F3AD),
            Emoji(id = 94, name = "Artist Palette", code = 0x1F3A8),
            Emoji(id = 95, name = "Thread", code = 0x1F9F5),
            Emoji(id = 96, name = "Yarn", code = 0x1F9F6),
            Emoji(id = 97, name = "Musical Score", code = 0x1F3BC),
            Emoji(id = 98, name = "Microphone", code = 0x1F3A4),
            Emoji(id = 99, name = "Headphone", code = 0x1F3A7),
            Emoji(id = 100, name = "Saxophone", code = 0x1F3B7),
            Emoji(id = 101, name = "Guitar", code = 0x1F3B8),
            Emoji(id = 102, name = "Musical Keyboard", code = 0x1F3B9),
            Emoji(id = 103, name = "Trumpet", code = 0x1F3BA),
            Emoji(id = 104, name = "Violin", code = 0x1F3BB),
            Emoji(id = 105, name = "Drum", code = 0x1F941),
            Emoji(id = 106, name = "Clapper Board", code = 0x1F3AC),
            Emoji(id = 107, name = "Bow and Arrow", code = 0x1F3F9)
        )
    }
}