package com.naposystems.pepito.utility.emojiManager.categories

import com.naposystems.pepito.model.emojiKeyboard.Emoji
import com.naposystems.pepito.model.emojiKeyboard.EmojiCategory

class FlagsCategory : EmojiCategory() {

    init {
        this.id = 8
        this.name = "Flags"
        this.emojiList = arrayListOf(
            Emoji(id = 1, name = "Chequered Flag", code = 0x1F3C1),
            Emoji(id = 2, name = "Triangular Flag", code = 0x1F6A9),
            Emoji(id = 3, name = "Crossed Flags", code = 0x1F38C),
            Emoji(id = 4, name = "Black Flag", code = 0x1F3F4),
            Emoji(id = 5, name = "White Flag", code = 0x1F3F3),
            Emoji(id = 6, name = "Rainbow Flag", code = 0x1F3F3),
            Emoji(id = 7, name = "Transgender Flag", code = 0x1F3F3),
            Emoji(id = 8, name = "Pirate Flag", code = 0x1F3F4),
            Emoji(id = 9, name = "Flag: Ascension Island", code = 0x1F1E6),
            Emoji(id = 10, name = "Flag: Andorra", code = 0x1F1E6),
            Emoji(id = 11, name = "Flag: United Arab Emirates", code = 0x1F1E6),
            Emoji(id = 12, name = "Flag: Afghanistan", code = 0x1F1E6),
            Emoji(id = 13, name = "Flag: Antigua & Barbuda", code = 0x1F1E6),
            Emoji(id = 14, name = "Flag: Anguilla", code = 0x1F1E6),
            Emoji(id = 15, name = "Flag: Albania", code = 0x1F1E6),
            Emoji(id = 16, name = "Flag: Armenia", code = 0x1F1E6),
            Emoji(id = 17, name = "Flag: Angola", code = 0x1F1E6),
            Emoji(id = 18, name = "Flag: Antarctica", code = 0x1F1E6),
            Emoji(id = 19, name = "Flag: Argentina", code = 0x1F1E6),
            Emoji(id = 20, name = "Flag: American Samoa", code = 0x1F1E6),
            Emoji(id = 21, name = "Flag: Austria", code = 0x1F1E6),
            Emoji(id = 22, name = "Flag: Australia", code = 0x1F1E6),
            Emoji(id = 23, name = "Flag: Aruba", code = 0x1F1E6),
            Emoji(id = 24, name = "Flag: Åland Islands", code = 0x1F1E6),
            Emoji(id = 25, name = "Flag: Azerbaijan", code = 0x1F1E6),
            Emoji(id = 26, name = "Flag: Bosnia & Herzegovina", code = 0x1F1E7),
            Emoji(id = 27, name = "Flag: Barbados", code = 0x1F1E7),
            Emoji(id = 28, name = "Flag: Bangladesh", code = 0x1F1E7),
            Emoji(id = 29, name = "Flag: Belgium", code = 0x1F1E7),
            Emoji(id = 30, name = "Flag: Burkina Faso", code = 0x1F1E7),
            Emoji(id = 31, name = "Flag: Bulgaria", code = 0x1F1E7),
            Emoji(id = 32, name = "Flag: Bahrain", code = 0x1F1E7),
            Emoji(id = 33, name = "Flag: Burundi", code = 0x1F1E7),
            Emoji(id = 34, name = "Flag: Benin", code = 0x1F1E7),
            Emoji(id = 35, name = "Flag: St. Barthélemy", code = 0x1F1E7),
            Emoji(id = 36, name = "Flag: Bermuda", code = 0x1F1E7),
            Emoji(id = 37, name = "Flag: Brunei", code = 0x1F1E7),
            Emoji(id = 38, name = "Flag: Bolivia", code = 0x1F1E7),
            Emoji(id = 39, name = "Flag: Caribbean Netherlands", code = 0x1F1E7),
            Emoji(id = 40, name = "Flag: Brazil", code = 0x1F1E7),
            Emoji(id = 41, name = "Flag: Bahamas", code = 0x1F1E7),
            Emoji(id = 42, name = "Flag: Bhutan", code = 0x1F1E7),
            Emoji(id = 43, name = "Flag: Bouvet Island", code = 0x1F1E7),
            Emoji(id = 44, name = "Flag: Botswana", code = 0x1F1E7),
            Emoji(id = 45, name = "Flag: Belarus", code = 0x1F1E7),
            Emoji(id = 46, name = "Flag: Belize", code = 0x1F1E7),
            Emoji(id = 47, name = "Flag: Canada", code = 0x1F1E8),
            Emoji(id = 48, name = "Flag: Cocos (Keeling), Islands", code = 0x1F1E8),
            Emoji(id = 49, name = "Flag: Congo - Kinshasa", code = 0x1F1E8),
            Emoji(id = 50, name = "Flag: Central African Republic", code = 0x1F1E8),
            Emoji(id = 51, name = "Flag: Congo - Brazzaville", code = 0x1F1E8),
            Emoji(id = 52, name = "Flag: Switzerland", code = 0x1F1E8),
            Emoji(id = 53, name = "Flag: Côte d’Ivoire", code = 0x1F1E8),
            Emoji(id = 54, name = "Flag: Cook Islands", code = 0x1F1E8),
            Emoji(id = 55, name = "Flag: Chile", code = 0x1F1E8),
            Emoji(id = 56, name = "Flag: Cameroon", code = 0x1F1E8),
            Emoji(id = 57, name = "Flag: China", code = 0x1F1E8),
            Emoji(id = 58, name = "Flag: Colombia", code = 0x1F1E8),
            Emoji(id = 59, name = "Flag: Clipperton Island", code = 0x1F1E8),
            Emoji(id = 60, name = "Flag: Costa Rica", code = 0x1F1E8),
            Emoji(id = 61, name = "Flag: Cuba", code = 0x1F1E8),
            Emoji(id = 62, name = "Flag: Cape Verde", code = 0x1F1E8),
            Emoji(id = 63, name = "Flag: Curaçao", code = 0x1F1E8),
            Emoji(id = 64, name = "Flag: Christmas Island", code = 0x1F1E8),
            Emoji(id = 65, name = "Flag: Cyprus", code = 0x1F1E8),
            Emoji(id = 66, name = "Flag: Czechia", code = 0x1F1E8),
            Emoji(id = 67, name = "Flag: Germany", code = 0x1F1E9),
            Emoji(id = 68, name = "Flag: Diego Garcia", code = 0x1F1E9),
            Emoji(id = 69, name = "Flag: Djibouti", code = 0x1F1E9),
            Emoji(id = 70, name = "Flag: Denmark", code = 0x1F1E9),
            Emoji(id = 71, name = "Flag: Dominica", code = 0x1F1E9),
            Emoji(id = 72, name = "Flag: Dominican Republic", code = 0x1F1E9),
            Emoji(id = 73, name = "Flag: Algeria", code = 0x1F1E9),
            Emoji(id = 74, name = "Flag: Ceuta & Melilla", code = 0x1F1EA),
            Emoji(id = 75, name = "Flag: Ecuador", code = 0x1F1EA),
            Emoji(id = 76, name = "Flag: Estonia", code = 0x1F1EA),
            Emoji(id = 77, name = "Flag: Egypt", code = 0x1F1EA),
            Emoji(id = 78, name = "Flag: Western Sahara", code = 0x1F1EA),
            Emoji(id = 79, name = "Flag: Eritrea", code = 0x1F1EA),
            Emoji(id = 80, name = "Flag: Spain", code = 0x1F1EA),
            Emoji(id = 81, name = "Flag: Ethiopia", code = 0x1F1EA),
            Emoji(id = 82, name = "Flag: European Union", code = 0x1F1EA),
            Emoji(id = 83, name = "Flag: Finland", code = 0x1F1EB),
            Emoji(id = 84, name = "Flag: Fiji", code = 0x1F1EB),
            Emoji(id = 85, name = "Flag: Falkland Islands", code = 0x1F1EB),
            Emoji(id = 86, name = "Flag: Micronesia", code = 0x1F1EB),
            Emoji(id = 87, name = "Flag: Faroe Islands", code = 0x1F1EB),
            Emoji(id = 88, name = "Flag: France", code = 0x1F1EB),
            Emoji(id = 89, name = "Flag: Gabon", code = 0x1F1EC),
            Emoji(id = 90, name = "Flag: United Kingdom", code = 0x1F1EC),
            Emoji(id = 91, name = "Flag: Grenada", code = 0x1F1EC),
            Emoji(id = 92, name = "Flag: Georgia", code = 0x1F1EC),
            Emoji(id = 93, name = "Flag: French Guiana", code = 0x1F1EC),
            Emoji(id = 94, name = "Flag: Guernsey", code = 0x1F1EC),
            Emoji(id = 95, name = "Flag: Ghana", code = 0x1F1EC),
            Emoji(id = 96, name = "Flag: Gibraltar", code = 0x1F1EC),
            Emoji(id = 97, name = "Flag: Greenland", code = 0x1F1EC),
            Emoji(id = 98, name = "Flag: Gambia", code = 0x1F1EC),
            Emoji(id = 99, name = "Flag: Guinea", code = 0x1F1EC),
            Emoji(id = 100, name = "Flag: Guadeloupe", code = 0x1F1EC),
            Emoji(id = 101, name = "Flag: Equatorial Guinea", code = 0x1F1EC),
            Emoji(id = 102, name = "Flag: Greece", code = 0x1F1EC),
            Emoji(id = 103, name = "Flag: South Georgia & South Sandwich Islands", code = 0x1F1EC),
            Emoji(id = 104, name = "Flag: Guatemala", code = 0x1F1EC),
            Emoji(id = 105, name = "Flag: Guam", code = 0x1F1EC),
            Emoji(id = 106, name = "Flag: Guinea-Bissau", code = 0x1F1EC),
            Emoji(id = 107, name = "Flag: Guyana", code = 0x1F1EC),
            Emoji(id = 108, name = "Flag: Hong Kong SAR China", code = 0x1F1ED),
            Emoji(id = 109, name = "Flag: Heard & McDonald Islands", code = 0x1F1ED),
            Emoji(id = 110, name = "Flag: Honduras", code = 0x1F1ED),
            Emoji(id = 111, name = "Flag: Croatia", code = 0x1F1ED),
            Emoji(id = 112, name = "Flag: Haiti", code = 0x1F1ED),
            Emoji(id = 113, name = "Flag: Hungary", code = 0x1F1ED),
            Emoji(id = 114, name = "Flag: Canary Islands", code = 0x1F1EE),
            Emoji(id = 115, name = "Flag: Indonesia", code = 0x1F1EE),
            Emoji(id = 116, name = "Flag: Ireland", code = 0x1F1EE),
            Emoji(id = 117, name = "Flag: Israel", code = 0x1F1EE),
            Emoji(id = 118, name = "Flag: Isle of Man", code = 0x1F1EE),
            Emoji(id = 119, name = "Flag: India", code = 0x1F1EE),
            Emoji(id = 120, name = "Flag: British Indian Ocean Territory", code = 0x1F1EE),
            Emoji(id = 121, name = "Flag: Iraq", code = 0x1F1EE),
            Emoji(id = 122, name = "Flag: Iran", code = 0x1F1EE),
            Emoji(id = 123, name = "Flag: Iceland", code = 0x1F1EE),
            Emoji(id = 124, name = "Flag: Italy", code = 0x1F1EE),
            Emoji(id = 125, name = "Flag: Jersey", code = 0x1F1EF),
            Emoji(id = 126, name = "Flag: Jamaica", code = 0x1F1EF),
            Emoji(id = 127, name = "Flag: Jordan", code = 0x1F1EF),
            Emoji(id = 128, name = "Flag: Japan", code = 0x1F1EF),
            Emoji(id = 129, name = "Flag: Kenya", code = 0x1F1F0),
            Emoji(id = 130, name = "Flag: Kyrgyzstan", code = 0x1F1F0),
            Emoji(id = 131, name = "Flag: Cambodia", code = 0x1F1F0),
            Emoji(id = 132, name = "Flag: Kiribati", code = 0x1F1F0),
            Emoji(id = 133, name = "Flag: Comoros", code = 0x1F1F0),
            Emoji(id = 134, name = "Flag: St. Kitts & Nevis", code = 0x1F1F0),
            Emoji(id = 135, name = "Flag: North Korea", code = 0x1F1F0),
            Emoji(id = 136, name = "Flag: South Korea", code = 0x1F1F0),
            Emoji(id = 137, name = "Flag: Kuwait", code = 0x1F1F0),
            Emoji(id = 138, name = "Flag: Cayman Islands", code = 0x1F1F0),
            Emoji(id = 139, name = "Flag: Kazakhstan", code = 0x1F1F0),
            Emoji(id = 140, name = "Flag: Laos", code = 0x1F1F1),
            Emoji(id = 141, name = "Flag: Lebanon", code = 0x1F1F1),
            Emoji(id = 142, name = "Flag: St. Lucia", code = 0x1F1F1),
            Emoji(id = 143, name = "Flag: Liechtenstein", code = 0x1F1F1),
            Emoji(id = 144, name = "Flag: Sri Lanka", code = 0x1F1F1),
            Emoji(id = 145, name = "Flag: Liberia", code = 0x1F1F1),
            Emoji(id = 146, name = "Flag: Lesotho", code = 0x1F1F1),
            Emoji(id = 147, name = "Flag: Lithuania", code = 0x1F1F1),
            Emoji(id = 148, name = "Flag: Luxembourg", code = 0x1F1F1),
            Emoji(id = 149, name = "Flag: Latvia", code = 0x1F1F1),
            Emoji(id = 150, name = "Flag: Libya", code = 0x1F1F1),
            Emoji(id = 151, name = "Flag: Morocco", code = 0x1F1F2),
            Emoji(id = 152, name = "Flag: Monaco", code = 0x1F1F2),
            Emoji(id = 153, name = "Flag: Moldova", code = 0x1F1F2),
            Emoji(id = 154, name = "Flag: Montenegro", code = 0x1F1F2),
            Emoji(id = 155, name = "Flag: St. Martin", code = 0x1F1F2),
            Emoji(id = 156, name = "Flag: Madagascar", code = 0x1F1F2),
            Emoji(id = 157, name = "Flag: Marshall Islands", code = 0x1F1F2),
            Emoji(id = 158, name = "Flag: North Macedonia", code = 0x1F1F2),
            Emoji(id = 159, name = "Flag: Mali", code = 0x1F1F2),
            Emoji(id = 160, name = "Flag: Myanmar (Burma),", code = 0x1F1F2),
            Emoji(id = 161, name = "Flag: Mongolia", code = 0x1F1F2),
            Emoji(id = 162, name = "Flag: Macao Sar China", code = 0x1F1F2),
            Emoji(id = 163, name = "Flag: Northern Mariana Islands", code = 0x1F1F2),
            Emoji(id = 164, name = "Flag: Martinique", code = 0x1F1F2),
            Emoji(id = 165, name = "Flag: Mauritania", code = 0x1F1F2),
            Emoji(id = 166, name = "Flag: Montserrat", code = 0x1F1F2),
            Emoji(id = 167, name = "Flag: Malta", code = 0x1F1F2),
            Emoji(id = 168, name = "Flag: Mauritius", code = 0x1F1F2),
            Emoji(id = 169, name = "Flag: Maldives", code = 0x1F1F2),
            Emoji(id = 170, name = "Flag: Malawi", code = 0x1F1F2),
            Emoji(id = 171, name = "Flag: Mexico", code = 0x1F1F2),
            Emoji(id = 172, name = "Flag: Malaysia", code = 0x1F1F2),
            Emoji(id = 173, name = "Flag: Mozambique", code = 0x1F1F2),
            Emoji(id = 174, name = "Flag: Namibia", code = 0x1F1F3),
            Emoji(id = 175, name = "Flag: New Caledonia", code = 0x1F1F3),
            Emoji(id = 176, name = "Flag: Niger", code = 0x1F1F3),
            Emoji(id = 177, name = "Flag: Norfolk Island", code = 0x1F1F3),
            Emoji(id = 178, name = "Flag: Nigeria", code = 0x1F1F3),
            Emoji(id = 179, name = "Flag: Nicaragua", code = 0x1F1F3),
            Emoji(id = 180, name = "Flag: Netherlands", code = 0x1F1F3),
            Emoji(id = 181, name = "Flag: Norway", code = 0x1F1F3),
            Emoji(id = 182, name = "Flag: Nepal", code = 0x1F1F3),
            Emoji(id = 183, name = "Flag: Nauru", code = 0x1F1F3),
            Emoji(id = 184, name = "Flag: Niue", code = 0x1F1F3),
            Emoji(id = 185, name = "Flag: New Zealand", code = 0x1F1F3),
            Emoji(id = 186, name = "Flag: Oman", code = 0x1F1F4),
            Emoji(id = 187, name = "Flag: Panama", code = 0x1F1F5),
            Emoji(id = 188, name = "Flag: Peru", code = 0x1F1F5),
            Emoji(id = 189, name = "Flag: French Polynesia", code = 0x1F1F5),
            Emoji(id = 190, name = "Flag: Papua New Guinea", code = 0x1F1F5),
            Emoji(id = 191, name = "Flag: Philippines", code = 0x1F1F5),
            Emoji(id = 192, name = "Flag: Pakistan", code = 0x1F1F5),
            Emoji(id = 193, name = "Flag: Poland", code = 0x1F1F5),
            Emoji(id = 194, name = "Flag: St. Pierre & Miquelon", code = 0x1F1F5),
            Emoji(id = 195, name = "Flag: Pitcairn Islands", code = 0x1F1F5),
            Emoji(id = 196, name = "Flag: Puerto Rico", code = 0x1F1F5),
            Emoji(id = 197, name = "Flag: Palestinian Territories", code = 0x1F1F5),
            Emoji(id = 198, name = "Flag: Portugal", code = 0x1F1F5),
            Emoji(id = 199, name = "Flag: Palau", code = 0x1F1F5),
            Emoji(id = 200, name = "Flag: Paraguay", code = 0x1F1F5),
            Emoji(id = 201, name = "Flag: Qatar", code = 0x1F1F6),
            Emoji(id = 202, name = "Flag: Réunion", code = 0x1F1F7),
            Emoji(id = 203, name = "Flag: Romania", code = 0x1F1F7),
            Emoji(id = 204, name = "Flag: Serbia", code = 0x1F1F7),
            Emoji(id = 205, name = "Flag: Russia", code = 0x1F1F7),
            Emoji(id = 206, name = "Flag: Rwanda", code = 0x1F1F7),
            Emoji(id = 207, name = "Flag: Saudi Arabia", code = 0x1F1F8),
            Emoji(id = 208, name = "Flag: Solomon Islands", code = 0x1F1F8),
            Emoji(id = 209, name = "Flag: Seychelles", code = 0x1F1F8),
            Emoji(id = 210, name = "Flag: Sudan", code = 0x1F1F8),
            Emoji(id = 211, name = "Flag: Sweden", code = 0x1F1F8),
            Emoji(id = 212, name = "Flag: Singapore", code = 0x1F1F8),
            Emoji(id = 213, name = "Flag: St. Helena", code = 0x1F1F8),
            Emoji(id = 214, name = "Flag: Slovenia", code = 0x1F1F8),
            Emoji(id = 215, name = "Flag: Svalbard & Jan Mayen", code = 0x1F1F8),
            Emoji(id = 216, name = "Flag: Slovakia", code = 0x1F1F8),
            Emoji(id = 217, name = "Flag: Sierra Leone", code = 0x1F1F8),
            Emoji(id = 218, name = "Flag: San Marino", code = 0x1F1F8),
            Emoji(id = 219, name = "Flag: Senegal", code = 0x1F1F8),
            Emoji(id = 220, name = "Flag: Somalia", code = 0x1F1F8),
            Emoji(id = 221, name = "Flag: Suriname", code = 0x1F1F8),
            Emoji(id = 222, name = "Flag: South Sudan", code = 0x1F1F8),
            Emoji(id = 223, name = "Flag: São Tomé & Príncipe", code = 0x1F1F8),
            Emoji(id = 224, name = "Flag: El Salvador", code = 0x1F1F8),
            Emoji(id = 225, name = "Flag: Sint Maarten", code = 0x1F1F8),
            Emoji(id = 226, name = "Flag: Syria", code = 0x1F1F8),
            Emoji(id = 227, name = "Flag: Eswatini", code = 0x1F1F8),
            Emoji(id = 228, name = "Flag: Tristan Da Cunha", code = 0x1F1F9),
            Emoji(id = 229, name = "Flag: Turks & Caicos Islands", code = 0x1F1F9),
            Emoji(id = 230, name = "Flag: Chad", code = 0x1F1F9),
            Emoji(id = 231, name = "Flag: French Southern Territories", code = 0x1F1F9),
            Emoji(id = 232, name = "Flag: Togo", code = 0x1F1F9),
            Emoji(id = 233, name = "Flag: Thailand", code = 0x1F1F9),
            Emoji(id = 234, name = "Flag: Tajikistan", code = 0x1F1F9),
            Emoji(id = 235, name = "Flag: Tokelau", code = 0x1F1F9),
            Emoji(id = 236, name = "Flag: Timor-Leste", code = 0x1F1F9),
            Emoji(id = 237, name = "Flag: Turkmenistan", code = 0x1F1F9),
            Emoji(id = 238, name = "Flag: Tunisia", code = 0x1F1F9),
            Emoji(id = 239, name = "Flag: Tonga", code = 0x1F1F9),
            Emoji(id = 240, name = "Flag: Turkey", code = 0x1F1F9),
            Emoji(id = 241, name = "Flag: Trinidad & Tobago", code = 0x1F1F9),
            Emoji(id = 242, name = "Flag: Tuvalu", code = 0x1F1F9),
            Emoji(id = 243, name = "Flag: Taiwan", code = 0x1F1F9),
            Emoji(id = 244, name = "Flag: Tanzania", code = 0x1F1F9),
            Emoji(id = 245, name = "Flag: Ukraine", code = 0x1F1FA),
            Emoji(id = 246, name = "Flag: Uganda", code = 0x1F1FA),
            Emoji(id = 247, name = "Flag: U.S. Outlying Islands", code = 0x1F1FA),
            Emoji(id = 248, name = "Flag: United Nations", code = 0x1F1FA),
            Emoji(id = 249, name = "Flag: United States", code = 0x1F1FA),
            Emoji(id = 250, name = "Flag: Uruguay", code = 0x1F1FA),
            Emoji(id = 251, name = "Flag: Uzbekistan", code = 0x1F1FA),
            Emoji(id = 252, name = "Flag: Vatican City", code = 0x1F1FB),
            Emoji(id = 253, name = "Flag: St. Vincent & Grenadines", code = 0x1F1FB),
            Emoji(id = 254, name = "Flag: Venezuela", code = 0x1F1FB),
            Emoji(id = 255, name = "Flag: British Virgin Islands", code = 0x1F1FB),
            Emoji(id = 256, name = "Flag: U.S. Virgin Islands", code = 0x1F1FB),
            Emoji(id = 257, name = "Flag: Vietnam", code = 0x1F1FB),
            Emoji(id = 258, name = "Flag: Vanuatu", code = 0x1F1FB),
            Emoji(id = 259, name = "Flag: Wallis & Futuna", code = 0x1F1FC),
            Emoji(id = 260, name = "Flag: Samoa", code = 0x1F1FC),
            Emoji(id = 261, name = "Flag: Kosovo", code = 0x1F1FD),
            Emoji(id = 262, name = "Flag: Yemen", code = 0x1F1FE),
            Emoji(id = 263, name = "Flag: Mayotte", code = 0x1F1FE),
            Emoji(id = 264, name = "Flag: South Africa", code = 0x1F1FF),
            Emoji(id = 265, name = "Flag: Zambia", code = 0x1F1FF),
            Emoji(id = 266, name = "Flag: Zimbabwe", code = 0x1F1FF),
            Emoji(id = 267, name = "Flag: England", code = 0x1F3F4),
            Emoji(id = 268, name = "Flag: Scotland", code = 0x1F3F4),
            Emoji(id = 269, name = "Flag: Wales", code = 0x1F3F4),
            Emoji(id = 270, name = "Flag for Texas (US-TX),", code = 0x1F3F4)
        )
    }
}