package com.naposystems.pepito.utility.emojiManager.categories

import com.naposystems.pepito.model.emojiKeyboard.Emoji
import com.naposystems.pepito.model.emojiKeyboard.EmojiCategory

class ObjectsCategory : EmojiCategory() {

    init {
        this.id = 6
        this.name = "Objects"
        this.emojiList = arrayListOf(
            Emoji(id = 1, name = "Love Letter", code = 0x1F48C),
            Emoji(id = 2, name = "Hole", code = 0x1F573),
            Emoji(id = 3, name = "Bomb", code = 0x1F4A3),
            Emoji(id = 4, name = "Person Taking Bath", code = 0x1F6C0),
            Emoji(id = 5, name = "Person in Bed", code = 0x1F6CC),
            Emoji(id = 6, name = "Kitchen Knife", code = 0x1F52A),
            Emoji(id = 7, name = "Amphora", code = 0x1F3FA),
            Emoji(id = 8, name = "World Map", code = 0x1F5FA),
            Emoji(id = 9, name = "Compass", code = 0x1F9ED),
            Emoji(id = 10, name = "Brick", code = 0x1F9F1),
            Emoji(id = 11, name = "Barber Pole", code = 0x1F488),
            Emoji(id = 12, name = "Manual Wheelchair", code = 0x1F9BD),
            Emoji(id = 13, name = "Motorized Wheelchair", code = 0x1F9BC),
            Emoji(id = 14, name = "Oil Drum", code = 0x1F6E2),
            Emoji(id = 15, name = "Bellhop Bell", code = 0x1F6CE),
            Emoji(id = 16, name = "Luggage", code = 0x1F9F3),
            Emoji(id = 17, name = "Hourglass Done", code = 0x231B),
            Emoji(id = 18, name = "Hourglass Not Done", code = 0x23F3),
            Emoji(id = 19, name = "Watch", code = 0x231A),
            Emoji(id = 20, name = "Alarm Clock", code = 0x23F0),
            Emoji(id = 21, name = "Stopwatch", code = 0x23F1),
            Emoji(id = 22, name = "Timer Clock", code = 0x23F2),
            Emoji(id = 23, name = "Mantelpiece Clock", code = 0x1F570),
            Emoji(id = 24, name = "Thermometer", code = 0x1F321),
            Emoji(id = 25, name = "Umbrella on Ground", code = 0x26F1),
            Emoji(id = 26, name = "Firecracker", code = 0x1F9E8),
            Emoji(id = 27, name = "Balloon", code = 0x1F388),
            Emoji(id = 28, name = "Party Popper", code = 0x1F389),
            Emoji(id = 29, name = "Confetti Ball", code = 0x1F38A),
            Emoji(id = 30, name = "Japanese Dolls", code = 0x1F38E),
            Emoji(id = 31, name = "Carp Streamer", code = 0x1F38F),
            Emoji(id = 32, name = "Wind Chime", code = 0x1F390),
            Emoji(id = 33, name = "Red Envelope", code = 0x1F9E7),
            Emoji(id = 34, name = "Ribbon", code = 0x1F380),
            Emoji(id = 35, name = "Wrapped Gift", code = 0x1F381),
            Emoji(id = 36, name = "Diving Mask", code = 0x1F93F),
            Emoji(id = 37, name = "Yo-Yo", code = 0x1FA80),
            Emoji(id = 38, name = "Kite", code = 0x1FA81),
            Emoji(id = 39, name = "Crystal Ball", code = 0x1F52E),
            Emoji(id = 40, name = "Nazar Amulet", code = 0x1F9FF),
            Emoji(id = 41, name = "Joystick", code = 0x1F579),
            Emoji(id = 42, name = "Teddy Bear", code = 0x1F9F8),
            Emoji(id = 43, name = "Framed Picture", code = 0x1F5BC),
            Emoji(id = 44, name = "Thread", code = 0x1F9F5),
            Emoji(id = 45, name = "Yarn", code = 0x1F9F6),
            Emoji(id = 46, name = "Shopping Bags", code = 0x1F6CD),
            Emoji(id = 47, name = "Prayer Beads", code = 0x1F4FF),
            Emoji(id = 48, name = "Gem Stone", code = 0x1F48E),
            Emoji(id = 49, name = "Postal Horn", code = 0x1F4EF),
            Emoji(id = 50, name = "Studio Microphone", code = 0x1F399),
            Emoji(id = 51, name = "Level Slider", code = 0x1F39A),
            Emoji(id = 52, name = "Control Knobs", code = 0x1F39B),
            Emoji(id = 53, name = "Radio", code = 0x1F4FB),
            Emoji(id = 54, name = "Banjo", code = 0x1FA95),
            Emoji(id = 55, name = "Mobile Phone", code = 0x1F4F1),
            Emoji(id = 56, name = "Mobile Phone with Arrow", code = 0x1F4F2),
            Emoji(id = 57, name = "Telephone", code = 0x260E),
            Emoji(id = 58, name = "Telephone Receiver", code = 0x1F4DE),
            Emoji(id = 59, name = "Pager", code = 0x1F4DF),
            Emoji(id = 60, name = "Fax Machine", code = 0x1F4E0),
            Emoji(id = 61, name = "Battery", code = 0x1F50B),
            Emoji(id = 62, name = "Electric Plug", code = 0x1F50C),
            Emoji(id = 63, name = "Laptop", code = 0x1F4BB),
            Emoji(id = 64, name = "Desktop Computer", code = 0x1F5A5),
            Emoji(id = 65, name = "Printer", code = 0x1F5A8),
            Emoji(id = 66, name = "Keyboard", code = 0x2328),
            Emoji(id = 67, name = "Computer Mouse", code = 0x1F5B1),
            Emoji(id = 68, name = "Trackball", code = 0x1F5B2),
            Emoji(id = 69, name = "Computer Disk", code = 0x1F4BD),
            Emoji(id = 70, name = "Floppy Disk", code = 0x1F4BE),
            Emoji(id = 71, name = "Optical Disk", code = 0x1F4BF),
            Emoji(id = 72, name = "DVD", code = 0x1F4C0),
            Emoji(id = 73, name = "Abacus", code = 0x1F9EE),
            Emoji(id = 74, name = "Movie Camera", code = 0x1F3A5),
            Emoji(id = 75, name = "Film Frames", code = 0x1F39E),
            Emoji(id = 76, name = "Film Projector", code = 0x1F4FD),
            Emoji(id = 77, name = "Television", code = 0x1F4FA),
            Emoji(id = 78, name = "Camera", code = 0x1F4F7),
            Emoji(id = 79, name = "Camera with Flash", code = 0x1F4F8),
            Emoji(id = 80, name = "Video Camera", code = 0x1F4F9),
            Emoji(id = 81, name = "Videocassette", code = 0x1F4FC),
            Emoji(id = 82, name = "Magnifying Glass Tilted Left", code = 0x1F50D),
            Emoji(id = 83, name = "Magnifying Glass Tilted Right", code = 0x1F50E),
            Emoji(id = 84, name = "Candle", code = 0x1F56F),
            Emoji(id = 85, name = "Light Bulb", code = 0x1F4A1),
            Emoji(id = 86, name = "Flashlight", code = 0x1F526),
            Emoji(id = 87, name = "Red Paper Lantern", code = 0x1F3EE),
            Emoji(id = 88, name = "Diya Lamp", code = 0x1FA94),
            Emoji(id = 89, name = "Notebook with Decorative Cover", code = 0x1F4D4),
            Emoji(id = 90, name = "Closed Book", code = 0x1F4D5),
            Emoji(id = 91, name = "Open Book", code = 0x1F4D6),
            Emoji(id = 92, name = "Green Book", code = 0x1F4D7),
            Emoji(id = 93, name = "Blue Book", code = 0x1F4D8),
            Emoji(id = 94, name = "Orange Book", code = 0x1F4D9),
            Emoji(id = 95, name = "Books", code = 0x1F4DA),
            Emoji(id = 96, name = "Notebook", code = 0x1F4D3),
            Emoji(id = 97, name = "Page with Curl", code = 0x1F4C3),
            Emoji(id = 98, name = "Scroll", code = 0x1F4DC),
            Emoji(id = 99, name = "Page Facing Up", code = 0x1F4C4),
            Emoji(id = 100, name = "Newspaper", code = 0x1F4F0),
            Emoji(id = 101, name = "Rolled-Up Newspaper", code = 0x1F5DE),
            Emoji(id = 102, name = "Bookmark Tabs", code = 0x1F4D1),
            Emoji(id = 103, name = "Bookmark", code = 0x1F516),
            Emoji(id = 104, name = "Label", code = 0x1F3F7),
            Emoji(id = 105, name = "Money Bag", code = 0x1F4B0),
            Emoji(id = 106, name = "Yen Banknote", code = 0x1F4B4),
            Emoji(id = 107, name = "Dollar Banknote", code = 0x1F4B5),
            Emoji(id = 108, name = "Euro Banknote", code = 0x1F4B6),
            Emoji(id = 109, name = "Pound Banknote", code = 0x1F4B7),
            Emoji(id = 110, name = "Money with Wings", code = 0x1F4B8),
            Emoji(id = 111, name = "Credit Card", code = 0x1F4B3),
            Emoji(id = 112, name = "Receipt", code = 0x1F9FE),
            Emoji(id = 113, name = "Envelope", code = 0x2709),
            Emoji(id = 114, name = "E-Mail", code = 0x1F4E7),
            Emoji(id = 115, name = "Incoming Envelope", code = 0x1F4E8),
            Emoji(id = 116, name = "Envelope with Arrow", code = 0x1F4E9),
            Emoji(id = 117, name = "Outbox Tray", code = 0x1F4E4),
            Emoji(id = 118, name = "Inbox Tray", code = 0x1F4E5),
            Emoji(id = 119, name = "Package", code = 0x1F4E6),
            Emoji(id = 120, name = "Closed Mailbox with Raised Flag", code = 0x1F4EB),
            Emoji(id = 121, name = "Closed Mailbox with Lowered Flag", code = 0x1F4EA),
            Emoji(id = 122, name = "Open Mailbox with Raised Flag", code = 0x1F4EC),
            Emoji(id = 123, name = "Open Mailbox with Lowered Flag", code = 0x1F4ED),
            Emoji(id = 124, name = "Postbox", code = 0x1F4EE),
            Emoji(id = 125, name = "Ballot Box with Ballot", code = 0x1F5F3),
            Emoji(id = 126, name = "Pencil", code = 0x270F),
            Emoji(id = 127, name = "Black Nib", code = 0x2712),
            Emoji(id = 128, name = "Fountain Pen", code = 0x1F58B),
            Emoji(id = 129, name = "Pen", code = 0x1F58A),
            Emoji(id = 130, name = "Paintbrush", code = 0x1F58C),
            Emoji(id = 131, name = "Crayon", code = 0x1F58D),
            Emoji(id = 132, name = "Memo", code = 0x1F4DD),
            Emoji(id = 133, name = "File Folder", code = 0x1F4C1),
            Emoji(id = 134, name = "Open File Folder", code = 0x1F4C2),
            Emoji(id = 135, name = "Card Index Dividers", code = 0x1F5C2),
            Emoji(id = 136, name = "Calendar", code = 0x1F4C5),
            Emoji(id = 137, name = "Tear-Off Calendar", code = 0x1F4C6),
            Emoji(id = 138, name = "Spiral Notepad", code = 0x1F5D2),
            Emoji(id = 139, name = "Spiral Calendar", code = 0x1F5D3),
            Emoji(id = 140, name = "Card Index", code = 0x1F4C7),
            Emoji(id = 141, name = "Chart Increasing", code = 0x1F4C8),
            Emoji(id = 142, name = "Chart Decreasing", code = 0x1F4C9),
            Emoji(id = 143, name = "Bar Chart", code = 0x1F4CA),
            Emoji(id = 144, name = "Clipboard", code = 0x1F4CB),
            Emoji(id = 145, name = "Pushpin", code = 0x1F4CC),
            Emoji(id = 146, name = "Round Pushpin", code = 0x1F4CD),
            Emoji(id = 147, name = "Paperclip", code = 0x1F4CE),
            Emoji(id = 148, name = "Linked Paperclips", code = 0x1F587),
            Emoji(id = 149, name = "Straight Ruler", code = 0x1F4CF),
            Emoji(id = 150, name = "Triangular Ruler", code = 0x1F4D0),
            Emoji(id = 151, name = "Scissors", code = 0x2702),
            Emoji(id = 152, name = "Card File Box", code = 0x1F5C3),
            Emoji(id = 153, name = "File Cabinet", code = 0x1F5C4),
            Emoji(id = 154, name = "Wastebasket", code = 0x1F5D1),
            Emoji(id = 155, name = "Locked", code = 0x1F512),
            Emoji(id = 156, name = "Unlocked", code = 0x1F513),
            Emoji(id = 157, name = "Locked with Pen", code = 0x1F50F),
            Emoji(id = 158, name = "Locked with Key", code = 0x1F510),
            Emoji(id = 159, name = "Key", code = 0x1F511),
            Emoji(id = 160, name = "Old Key", code = 0x1F5DD),
            Emoji(id = 161, name = "Hammer", code = 0x1F528),
            Emoji(id = 162, name = "Axe", code = 0x1FA93),
            Emoji(id = 163, name = "Pick", code = 0x26CF),
            Emoji(id = 164, name = "Hammer and Pick", code = 0x2692),
            Emoji(id = 165, name = "Hammer and Wrench", code = 0x1F6E0),
            Emoji(id = 166, name = "Dagger", code = 0x1F5E1),
            Emoji(id = 167, name = "Crossed Swords", code = 0x2694),
            Emoji(id = 168, name = "Pistol", code = 0x1F52B),
            Emoji(id = 169, name = "Shield", code = 0x1F6E1),
            Emoji(id = 170, name = "Wrench", code = 0x1F527),
            Emoji(id = 171, name = "Nut and Bolt", code = 0x1F529),
            Emoji(id = 172, name = "Gear", code = 0x2699),
            Emoji(id = 173, name = "Clamp", code = 0x1F5DC),
            Emoji(id = 174, name = "Balance Scale", code = 0x2696),
            Emoji(id = 175, name = "Probing Cane", code = 0x1F9AF),
            Emoji(id = 176, name = "Link", code = 0x1F517),
            Emoji(id = 177, name = "Chains", code = 0x26D3),
            Emoji(id = 178, name = "Toolbox", code = 0x1F9F0),
            Emoji(id = 179, name = "Magnet", code = 0x1F9F2),
            Emoji(id = 180, name = "Alembic", code = 0x2697),
            Emoji(id = 181, name = "Test Tube", code = 0x1F9EA),
            Emoji(id = 182, name = "Petri Dish", code = 0x1F9EB),
            Emoji(id = 183, name = "DNA", code = 0x1F9EC),
            Emoji(id = 184, name = "Microscope", code = 0x1F52C),
            Emoji(id = 185, name = "Telescope", code = 0x1F52D),
            Emoji(id = 186, name = "Satellite Antenna", code = 0x1F4E1),
            Emoji(id = 187, name = "Syringe", code = 0x1F489),
            Emoji(id = 188, name = "Drop of Blood", code = 0x1FA78),
            Emoji(id = 189, name = "Pill", code = 0x1F48A),
            Emoji(id = 190, name = "Adhesive Bandage", code = 0x1FA79),
            Emoji(id = 191, name = "Stethoscope", code = 0x1FA7A),
            Emoji(id = 192, name = "Door", code = 0x1F6AA),
            Emoji(id = 193, name = "Bed", code = 0x1F6CF),
            Emoji(id = 194, name = "Couch and Lamp", code = 0x1F6CB),
            Emoji(id = 195, name = "Chair", code = 0x1FA91),
            Emoji(id = 196, name = "Toilet", code = 0x1F6BD),
            Emoji(id = 197, name = "Shower", code = 0x1F6BF),
            Emoji(id = 198, name = "Bathtub", code = 0x1F6C1),
            Emoji(id = 199, name = "Razor", code = 0x1FA92),
            Emoji(id = 200, name = "Lotion Bottle", code = 0x1F9F4),
            Emoji(id = 201, name = "Safety Pin", code = 0x1F9F7),
            Emoji(id = 202, name = "Broom", code = 0x1F9F9),
            Emoji(id = 203, name = "Basket", code = 0x1F9FA),
            Emoji(id = 204, name = "Roll of Paper", code = 0x1F9FB),
            Emoji(id = 205, name = "Soap", code = 0x1F9FC),
            Emoji(id = 206, name = "Sponge", code = 0x1F9FD),
            Emoji(id = 207, name = "Fire Extinguisher", code = 0x1F9EF),
            Emoji(id = 208, name = "Cigarette", code = 0x1F6AC),
            Emoji(id = 209, name = "Coffin", code = 0x26B0),
            Emoji(id = 210, name = "Funeral Urn", code = 0x26B1),
            Emoji(id = 211, name = "Moai", code = 0x1F5FF),
            Emoji(id = 212, name = "Potable Water", code = 0x1F6B0)
        )
    }
}