package com.naposystems.pepito.utility.emojiManager.categories

import com.naposystems.pepito.model.emojiKeyboard.Emoji
import com.naposystems.pepito.model.emojiKeyboard.EmojiCategory

class SymbolsCategory : EmojiCategory() {

    init {
        this.id = 7
        this.name = "Symbols"
        this.emojiList = arrayListOf(
            Emoji(id = 1, name = "Heart with Arrow", code = 0x1F498),
            Emoji(id = 2, name = "Heart with Ribbon", code = 0x1F49D),
            Emoji(id = 3, name = "Sparkling Heart", code = 0x1F496),
            Emoji(id = 4, name = "Growing Heart", code = 0x1F497),
            Emoji(id = 5, name = "Beating Heart", code = 0x1F493),
            Emoji(id = 6, name = "Revolving Hearts", code = 0x1F49E),
            Emoji(id = 7, name = "Two Hearts", code = 0x1F495),
            Emoji(id = 8, name = "Heart Decoration", code = 0x1F49F),
            Emoji(id = 9, name = "Heart Exclamation", code = 0x2763),
            Emoji(id = 10, name = "Broken Heart", code = 0x1F494),
            Emoji(id = 11, name = "Red Heart", code = 0x2764),
            Emoji(id = 12, name = "Orange Heart", code = 0x1F9E1),
            Emoji(id = 13, name = "Yellow Heart", code = 0x1F49B),
            Emoji(id = 14, name = "Green Heart", code = 0x1F49A),
            Emoji(id = 15, name = "Blue Heart", code = 0x1F499),
            Emoji(id = 16, name = "Purple Heart", code = 0x1F49C),
            Emoji(id = 16, name = "Purple Heart", code = 0x1F49C),
            Emoji(id = 17, name = "Brown Heart", code = 0x1F90E),
            Emoji(id = 18, name = "Black Heart", code = 0x1F5A4),
            Emoji(id = 19, name = "White Heart", code = 0x1F90D),
            Emoji(id = 20, name = "Hundred Points", code = 0x1F4AF),
            Emoji(id = 21, name = "Anger Symbol", code = 0x1F4A2),
            Emoji(id = 22, name = "Speech Balloon", code = 0x1F4AC),
            Emoji(id = 23, name = "Eye in Speech Bubble", code = 0x1F441),
            Emoji(id = 24, name = "Right Anger Bubble", code = 0x1F5EF),
            Emoji(id = 25, name = "Thought Balloon", code = 0x1F4AD),
            Emoji(id = 26, name = "Zzz", code = 0x1F4A4),
            Emoji(id = 27, name = "White Flower", code = 0x1F4AE),
            Emoji(id = 28, name = "Hot Springs", code = 0x2668),
            Emoji(id = 29, name = "Barber Pole", code = 0x1F488),
            Emoji(id = 30, name = "Stop Sign", code = 0x1F6D1),
            Emoji(id = 31, name = "Twelve O’Clock", code = 0x1F55B),
            Emoji(id = 32, name = "Twelve-Thirty", code = 0x1F567),
            Emoji(id = 33, name = "One O’Clock", code = 0x1F550),
            Emoji(id = 34, name = "One-Thirty", code = 0x1F55C),
            Emoji(id = 35, name = "Two O’Clock", code = 0x1F551),
            Emoji(id = 36, name = "Two-Thirty", code = 0x1F55D),
            Emoji(id = 37, name = "Three O’Clock", code = 0x1F552),
            Emoji(id = 38, name = "Three-Thirty", code = 0x1F55E),
            Emoji(id = 39, name = "Four O’Clock", code = 0x1F553),
            Emoji(id = 40, name = "Four-Thirty", code = 0x1F55F),
            Emoji(id = 41, name = "Five O’Clock", code = 0x1F554),
            Emoji(id = 42, name = "Five-Thirty", code = 0x1F560),
            Emoji(id = 43, name = "Six O’Clock", code = 0x1F555),
            Emoji(id = 44, name = "Six-Thirty", code = 0x1F561),
            Emoji(id = 45, name = "Seven O’Clock", code = 0x1F556),
            Emoji(id = 46, name = "Seven-Thirty", code = 0x1F562),
            Emoji(id = 47, name = "Eight O’Clock", code = 0x1F557),
            Emoji(id = 48, name = "Eight-Thirty", code = 0x1F563),
            Emoji(id = 49, name = "Nine O’Clock", code = 0x1F558),
            Emoji(id = 50, name = "Nine-Thirty", code = 0x1F564),
            Emoji(id = 51, name = "Ten O’Clock", code = 0x1F559),
            Emoji(id = 52, name = "Ten-Thirty", code = 0x1F565),
            Emoji(id = 53, name = "Eleven O’Clock", code = 0x1F55A),
            Emoji(id = 54, name = "Eleven-Thirty", code = 0x1F566),
            Emoji(id = 55, name = "Cyclone", code = 0x1F300),
            Emoji(id = 56, name = "Spade Suit", code = 0x2660),
            Emoji(id = 57, name = "Heart Suit", code = 0x2665),
            Emoji(id = 58, name = "Diamond Suit", code = 0x2666),
            Emoji(id = 59, name = "Club Suit", code = 0x2663),
            Emoji(id = 60, name = "Joker", code = 0x1F0CF),
            Emoji(id = 61, name = "Mahjong Red Dragon", code = 0x1F004),
            Emoji(id = 62, name = "Flower Playing Cards", code = 0x1F3B4),
            Emoji(id = 63, name = "Muted Speaker", code = 0x1F507),
            Emoji(id = 64, name = "Speaker Low Volume", code = 0x1F508),
            Emoji(id = 65, name = "Speaker Medium Volume", code = 0x1F509),
            Emoji(id = 66, name = "Speaker High Volume", code = 0x1F50A),
            Emoji(id = 67, name = "Loudspeaker", code = 0x1F4E2),
            Emoji(id = 68, name = "Megaphone", code = 0x1F4E3),
            Emoji(id = 69, name = "Postal Horn", code = 0x1F4EF),
            Emoji(id = 70, name = "Bell", code = 0x1F514),
            Emoji(id = 71, name = "Bell with Slash", code = 0x1F515),
            Emoji(id = 72, name = "Musical Note", code = 0x1F3B5),
            Emoji(id = 73, name = "Musical Notes", code = 0x1F3B6),
            Emoji(id = 74, name = "ATM Sign", code = 0x1F3E7),
            Emoji(id = 75, name = "Litter in Bin Sign", code = 0x1F6AE),
            Emoji(id = 76, name = "Potable Water", code = 0x1F6B0),
            Emoji(id = 77, name = "Wheelchair Symbol", code = 0x267F),
            Emoji(id = 78, name = "Men’s Room", code = 0x1F6B9),
            Emoji(id = 79, name = "Women’s Room", code = 0x1F6BA),
            Emoji(id = 80, name = "Restroom", code = 0x1F6BB),
            Emoji(id = 81, name = "Baby Symbol", code = 0x1F6BC),
            Emoji(id = 82, name = "Water Closet", code = 0x1F6BE),
            Emoji(id = 83, name = "Warning", code = 0x26A0),
            Emoji(id = 84, name = "Children Crossing", code = 0x1F6B8),
            Emoji(id = 85, name = "No Entry", code = 0x26D4),
            Emoji(id = 86, name = "Prohibited", code = 0x1F6AB),
            Emoji(id = 87, name = "No Bicycles", code = 0x1F6B3),
            Emoji(id = 88, name = "No Smoking", code = 0x1F6AD),
            Emoji(id = 89, name = "No Littering", code = 0x1F6AF),
            Emoji(id = 90, name = "Non-Potable Water", code = 0x1F6B1),
            Emoji(id = 91, name = "No Pedestrians", code = 0x1F6B7),
            Emoji(id = 92, name = "No One Under Eighteen", code = 0x1F51E),
            Emoji(id = 93, name = "Radioactive", code = 0x2622),
            Emoji(id = 94, name = "Biohazard", code = 0x2623),
            Emoji(id = 95, name = "Up Arrow", code = 0x2B06),
            Emoji(id = 96, name = "Up-Right Arrow", code = 0x2197),
            Emoji(id = 97, name = "Right Arrow", code = 0x27A1),
            Emoji(id = 98, name = "Down-Right Arrow", code = 0x2198),
            Emoji(id = 99, name = "Down Arrow", code = 0x2B07),
            Emoji(id = 100, name = "Down-Left Arrow", code = 0x2199),
            Emoji(id = 101, name = "Left Arrow", code = 0x2B05),
            Emoji(id = 102, name = "Up-Left Arrow", code = 0x2196),
            Emoji(id = 103, name = "Up-Down Arrow", code = 0x2195),
            Emoji(id = 104, name = "Left-Right Arrow", code = 0x2194),
            Emoji(id = 105, name = "Right Arrow Curving Left", code = 0x21A9),
            Emoji(id = 106, name = "Left Arrow Curving Right", code = 0x21AA),
            Emoji(id = 107, name = "Right Arrow Curving Up", code = 0x2934),
            Emoji(id = 108, name = "Right Arrow Curving Down", code = 0x2935),
            Emoji(id = 109, name = "Clockwise Vertical Arrows", code = 0x1F503),
            Emoji(id = 110, name = "Counterclockwise Arrows Button", code = 0x1F504),
            Emoji(id = 111, name = "Back Arrow", code = 0x1F519),
            Emoji(id = 112, name = "End Arrow", code = 0x1F51A),
            Emoji(id = 113, name = "On! Arrow", code = 0x1F51B),
            Emoji(id = 114, name = "Soon Arrow", code = 0x1F51C),
            Emoji(id = 115, name = "Top Arrow", code = 0x1F51D),
            Emoji(id = 116, name = "Place of Worship", code = 0x1F6D0),
            Emoji(id = 117, name = "Atom Symbol", code = 0x269B),
            Emoji(id = 118, name = "Om", code = 0x1F549),
            Emoji(id = 119, name = "Star of David", code = 0x2721),
            Emoji(id = 120, name = "Wheel of Dharma", code = 0x2638),
            Emoji(id = 121, name = "Yin Yang", code = 0x262F),
            Emoji(id = 122, name = "Latin Cross", code = 0x271D),
            Emoji(id = 123, name = "Orthodox Cross", code = 0x2626),
            Emoji(id = 124, name = "Star and Crescent", code = 0x262A),
            Emoji(id = 125, name = "Peace Symbol", code = 0x262E),
            Emoji(id = 126, name = "Menorah", code = 0x1F54E),
            Emoji(id = 127, name = "Dotted Six-Pointed Star", code = 0x1F52F),
            Emoji(id = 128, name = "Aries", code = 0x2648),
            Emoji(id = 129, name = "Taurus", code = 0x2649),
            Emoji(id = 130, name = "Gemini", code = 0x264A),
            Emoji(id = 131, name = "Cancer", code = 0x264B),
            Emoji(id = 132, name = "Leo", code = 0x264C),
            Emoji(id = 133, name = "Virgo", code = 0x264D),
            Emoji(id = 134, name = "Libra", code = 0x264E),
            Emoji(id = 135, name = "Scorpio", code = 0x264F),
            Emoji(id = 136, name = "Sagittarius", code = 0x2650),
            Emoji(id = 137, name = "Capricorn", code = 0x2651),
            Emoji(id = 138, name = "Aquarius", code = 0x2652),
            Emoji(id = 139, name = "Pisces", code = 0x2653),
            Emoji(id = 140, name = "Ophiuchus", code = 0x26CE),
            Emoji(id = 141, name = "Shuffle Tracks Button", code = 0x1F500),
            Emoji(id = 142, name = "Repeat Button", code = 0x1F501),
            Emoji(id = 143, name = "Repeat Single Button", code = 0x1F502),
            Emoji(id = 144, name = "Play Button", code = 0x25B6),
            Emoji(id = 145, name = "Fast-Forward Button", code = 0x23E9),
            Emoji(id = 146, name = "Reverse Button", code = 0x25C0),
            Emoji(id = 147, name = "Fast Reverse Button", code = 0x23EA),
            Emoji(id = 148, name = "Upwards Button", code = 0x1F53C),
            Emoji(id = 149, name = "Fast Up Button", code = 0x23EB),
            Emoji(id = 150, name = "Downwards Button", code = 0x1F53D),
            Emoji(id = 151, name = "Fast Down Button", code = 0x23EC),
            Emoji(id = 152, name = "Stop Button", code = 0x23F9),
            Emoji(id = 153, name = "Eject Button", code = 0x23CF),
            Emoji(id = 154, name = "Cinema", code = 0x1F3A6),
            Emoji(id = 155, name = "Dim Button", code = 0x1F505),
            Emoji(id = 156, name = "Bright Button", code = 0x1F506),
            Emoji(id = 157, name = "Antenna Bars", code = 0x1F4F6),
            Emoji(id = 158, name = "Vibration Mode", code = 0x1F4F3),
            Emoji(id = 159, name = "Mobile Phone Off", code = 0x1F4F4),
            Emoji(id = 160, name = "Multiplication Sign", code = 0x2716),
            Emoji(id = 161, name = "Plus Sign", code = 0x2795),
            Emoji(id = 162, name = "Minus Sign", code = 0x2796),
            Emoji(id = 163, name = "Division Sign", code = 0x2797),
            Emoji(id = 164, name = "Infinity", code = 0x267E),
            Emoji(id = 165, name = "Double Exclamation Mark", code = 0x203C),
            Emoji(id = 166, name = "Exclamation Question Mark", code = 0x2049),
            Emoji(id = 167, name = "Question Mark", code = 0x2753),
            Emoji(id = 168, name = "White Question Mark", code = 0x2754),
            Emoji(id = 169, name = "White Exclamation Mark", code = 0x2755),
            Emoji(id = 170, name = "Exclamation Mark", code = 0x2757),
            Emoji(id = 171, name = "Recycling Symbol", code = 0x267B),
            Emoji(id = 172, name = "Trident Emblem", code = 0x1F531),
            Emoji(id = 173, name = "Name Badge", code = 0x1F4DB),
            Emoji(id = 174, name = "Japanese Symbol for Beginner", code = 0x1F530),
            Emoji(id = 175, name = "Hollow Red Circle", code = 0x2B55),
            Emoji(id = 176, name = "Check Mark Button", code = 0x2705),
            Emoji(id = 177, name = "Check Box with Check", code = 0x2611),
            Emoji(id = 178, name = "Check Mark", code = 0x2714),
            Emoji(id = 179, name = "Cross Mark", code = 0x274C),
            Emoji(id = 180, name = "Cross Mark Button", code = 0x274E),
            Emoji(id = 181, name = "Curly Loop", code = 0x27B0),
            Emoji(id = 182, name = "Double Curly Loop", code = 0x27BF),
            Emoji(id = 183, name = "Part Alternation Mark", code = 0x303D),
            Emoji(id = 184, name = "Eight-Spoked Asterisk", code = 0x2733),
            Emoji(id = 185, name = "Eight-Pointed Star", code = 0x2734),
            Emoji(id = 186, name = "Sparkle", code = 0x2747),
            Emoji(id = 187, name = "Copyright", code = 0xA9),
            Emoji(id = 188, name = "Registered", code = 0xAE),
            Emoji(id = 189, name = "Trade Mark", code = 0x2122),
            Emoji(id = 190, name = "Keycap Number Sign", code = 0x23),
            Emoji(id = 191, name = "Keycap Digit Zero", code = 0x30),
            Emoji(id = 192, name = "Keycap Digit One", code = 0x31),
            Emoji(id = 193, name = "Keycap Digit Two", code = 0x32),
            Emoji(id = 194, name = "Keycap Digit Three", code = 0x33),
            Emoji(id = 195, name = "Keycap Digit Four", code = 0x34),
            Emoji(id = 196, name = "Keycap Digit Five", code = 0x35),
            Emoji(id = 197, name = "Keycap Digit Six", code = 0x36),
            Emoji(id = 198, name = "Keycap Digit Seven", code = 0x37),
            Emoji(id = 199, name = "Keycap Digit Eight", code = 0x38),
            Emoji(id = 200, name = "Keycap Digit Nine", code = 0x39),
            Emoji(id = 201, name = "Keycap: 10", code = 0x1F51F),
            Emoji(id = 202, name = "Input Latin Uppercase", code = 0x1F520),
            Emoji(id = 203, name = "Input Latin Lowercase", code = 0x1F521),
            Emoji(id = 204, name = "Input Numbers", code = 0x1F522),
            Emoji(id = 205, name = "Input Symbols", code = 0x1F523),
            Emoji(id = 206, name = "Input Latin Letters", code = 0x1F524),
            Emoji(id = 207, name = "A Button (Blood Type),", code = 0x1F170),
            Emoji(id = 208, name = "AB Button (Blood Type),", code = 0x1F18E),
            Emoji(id = 209, name = "B Button (Blood Type),", code = 0x1F171),
            Emoji(id = 210, name = "CL Button", code = 0x1F191),
            Emoji(id = 211, name = "Cool Button", code = 0x1F192),
            Emoji(id = 212, name = "Free Button", code = 0x1F193),
            Emoji(id = 213, name = "Information", code = 0x2139),
            Emoji(id = 214, name = "ID Button", code = 0x1F194),
            Emoji(id = 215, name = "Circled M", code = 0x24C2),
            Emoji(id = 216, name = "New Button", code = 0x1F195),
            Emoji(id = 217, name = "NG Button", code = 0x1F196),
            Emoji(id = 218, name = "O Button (Blood Type),", code = 0x1F17E),
            Emoji(id = 219, name = "OK Button", code = 0x1F197),
            Emoji(id = 220, name = "P Button", code = 0x1F17F),
            Emoji(id = 221, name = "SOS Button", code = 0x1F198),
            Emoji(id = 222, name = "Up! Button", code = 0x1F199),
            Emoji(id = 223, name = "Vs Button", code = 0x1F19A),
            Emoji(id = 224, name = "Japanese “Here” Button", code = 0x1F201),
            Emoji(id = 225, name = "Japanese “Service Charge” Button", code = 0x1F202),
            Emoji(id = 226, name = "Japanese “Monthly Amount” Button", code = 0x1F237),
            Emoji(id = 227, name = "Japanese “Not Free of Charge” Button", code = 0x1F236),
            Emoji(id = 228, name = "Japanese “Reserved” Button", code = 0x1F22F),
            Emoji(id = 229, name = "Japanese “Bargain” Button", code = 0x1F250),
            Emoji(id = 230, name = "Japanese “Discount” Button", code = 0x1F239),
            Emoji(id = 231, name = "Japanese “Free of Charge” Button", code = 0x1F21A),
            Emoji(id = 232, name = "Japanese “Prohibited” Button", code = 0x1F232),
            Emoji(id = 233, name = "Japanese “Acceptable” Button", code = 0x1F251),
            Emoji(id = 234, name = "Japanese “Application” Button", code = 0x1F238),
            Emoji(id = 235, name = "Japanese “Passing Grade” Button", code = 0x1F234),
            Emoji(id = 236, name = "Japanese “Vacancy” Button", code = 0x1F233),
            Emoji(id = 237, name = "Japanese “Congratulations” Button", code = 0x3297),
            Emoji(id = 238, name = "Japanese “Secret” Button", code = 0x3299),
            Emoji(id = 239, name = "Japanese “Open for Business” Button", code = 0x1F23A),
            Emoji(id = 240, name = "Japanese “No Vacancy” Button", code = 0x1F235),
            Emoji(id = 241, name = "Red Circle", code = 0x1F534),
            Emoji(id = 242, name = "Orange Circle", code = 0x1F7E0),
            Emoji(id = 243, name = "Yellow Circle", code = 0x1F7E1),
            Emoji(id = 244, name = "Green Circle", code = 0x1F7E2),
            Emoji(id = 245, name = "Blue Circle", code = 0x1F535),
            Emoji(id = 246, name = "Purple Circle", code = 0x1F7E3),
            Emoji(id = 247, name = "Brown Circle", code = 0x1F7E4),
            Emoji(id = 248, name = "Black Circle", code = 0x26AB),
            Emoji(id = 249, name = "White Circle", code = 0x26AA),
            Emoji(id = 250, name = "Red Square", code = 0x1F7E5),
            Emoji(id = 251, name = "Orange Square", code = 0x1F7E7),
            Emoji(id = 252, name = "Yellow Square", code = 0x1F7E8),
            Emoji(id = 253, name = "Green Square", code = 0x1F7E9),
            Emoji(id = 254, name = "Blue Square", code = 0x1F7E6),
            Emoji(id = 255, name = "Purple Square", code = 0x1F7EA),
            Emoji(id = 256, name = "Brown Square", code = 0x1F7EB),
            Emoji(id = 257, name = "Black Large Square", code = 0x2B1B),
            Emoji(id = 258, name = "White Large Square", code = 0x2B1C),
            Emoji(id = 259, name = "Black Medium Square", code = 0x25FC),
            Emoji(id = 260, name = "White Medium Square", code = 0x25FB),
            Emoji(id = 261, name = "Black Medium-Small Square", code = 0x25FE),
            Emoji(id = 262, name = "White Medium-Small Square", code = 0x25FD),
            Emoji(id = 263, name = "Black Small Square", code = 0x25AA),
            Emoji(id = 264, name = "White Small Square", code = 0x25AB),
            Emoji(id = 265, name = "Large Orange Diamond", code = 0x1F536),
            Emoji(id = 266, name = "Large Blue Diamond", code = 0x1F537),
            Emoji(id = 267, name = "Small Orange Diamond", code = 0x1F538),
            Emoji(id = 268, name = "Small Blue Diamond", code = 0x1F539),
            Emoji(id = 269, name = "Red Triangle Pointed Up", code = 0x1F53A),
            Emoji(id = 270, name = "Red Triangle Pointed Down", code = 0x1F53B),
            Emoji(id = 271, name = "Diamond with a Dot", code = 0x1F4A0),
            Emoji(id = 272, name = "White Square Button", code = 0x1F533),
            Emoji(id = 273, name = "Black Square Button", code = 0x1F532)
        )
    }
}