package com.naposystems.pepito.utility.emojiManager.categories

import com.naposystems.pepito.model.emojiKeyboard.Emoji
import com.naposystems.pepito.model.emojiKeyboard.EmojiCategory

class TravelAndPlacesCategory : EmojiCategory() {

    init {
        this.id = 5
        this.name = "Travel & Places"
        this.emojiList = arrayListOf(
            Emoji(id = 1, name = "Person Rowing Boat", code = 0x1F6A3),
            Emoji(id = 2, name = "Map of Japan", code = 0x1F5FE),
            Emoji(id = 3, name = "Snow-Capped Mountain", code = 0x1F3D4),
            Emoji(id = 4, name = "Mountain", code = 0x26F0),
            Emoji(id = 5, name = "Volcano", code = 0x1F30B),
            Emoji(id = 6, name = "Mount Fuji", code = 0x1F5FB),
            Emoji(id = 7, name = "Camping", code = 0x1F3D5),
            Emoji(id = 8, name = "Beach with Umbrella", code = 0x1F3D6),
            Emoji(id = 9, name = "Desert", code = 0x1F3DC),
            Emoji(id = 10, name = "Desert Island", code = 0x1F3DD),
            Emoji(id = 11, name = "National Park", code = 0x1F3DE),
            Emoji(id = 12, name = "Stadium", code = 0x1F3DF),
            Emoji(id = 13, name = "Classical Building", code = 0x1F3DB),
            Emoji(id = 14, name = "Building Construction", code = 0x1F3D7),
            Emoji(id = 15, name = "Houses", code = 0x1F3D8),
            Emoji(id = 16, name = "Derelict House", code = 0x1F3DA),
            Emoji(id = 17, name = "House", code = 0x1F3E0),
            Emoji(id = 18, name = "House with Garden", code = 0x1F3E1),
            Emoji(id = 19, name = "Office Building", code = 0x1F3E2),
            Emoji(id = 20, name = "Japanese Post Office", code = 0x1F3E3),
            Emoji(id = 21, name = "Post Office", code = 0x1F3E4),
            Emoji(id = 22, name = "Hospital", code = 0x1F3E5),
            Emoji(id = 23, name = "Bank", code = 0x1F3E6),
            Emoji(id = 24, name = "Hotel", code = 0x1F3E8),
            Emoji(id = 25, name = "Love Hotel", code = 0x1F3E9),
            Emoji(id = 26, name = "Convenience Store", code = 0x1F3EA),
            Emoji(id = 27, name = "School", code = 0x1F3EB),
            Emoji(id = 28, name = "Department Store", code = 0x1F3EC),
            Emoji(id = 29, name = "Factory", code = 0x1F3ED),
            Emoji(id = 30, name = "Japanese Castle", code = 0x1F3EF),
            Emoji(id = 31, name = "Castle", code = 0x1F3F0),
            Emoji(id = 32, name = "Wedding", code = 0x1F492),
            Emoji(id = 33, name = "Tokyo Tower", code = 0x1F5FC),
            Emoji(id = 34, name = "Statue of Liberty", code = 0x1F5FD),
            Emoji(id = 35, name = "Church", code = 0x26EA),
            Emoji(id = 36, name = "Mosque", code = 0x1F54C),
            Emoji(id = 37, name = "Hindu Temple", code = 0x1F6D5),
            Emoji(id = 38, name = "Synagogue", code = 0x1F54D),
            Emoji(id = 39, name = "Shinto Shrine", code = 0x26E9),
            Emoji(id = 40, name = "Kaaba", code = 0x1F54B),
            Emoji(id = 41, name = "Fountain", code = 0x26F2),
            Emoji(id = 42, name = "Tent", code = 0x26FA),
            Emoji(id = 43, name = "Foggy", code = 0x1F301),
            Emoji(id = 44, name = "Night with Stars", code = 0x1F303),
            Emoji(id = 45, name = "Cityscape", code = 0x1F3D9),
            Emoji(id = 46, name = "Sunrise Over Mountains", code = 0x1F304),
            Emoji(id = 47, name = "Sunrise", code = 0x1F305),
            Emoji(id = 48, name = "Cityscape at Dusk", code = 0x1F306),
            Emoji(id = 49, name = "Sunset", code = 0x1F307),
            Emoji(id = 50, name = "Bridge at Night", code = 0x1F309),
            Emoji(id = 51, name = "Carousel Horse", code = 0x1F3A0),
            Emoji(id = 52, name = "Ferris Wheel", code = 0x1F3A1),
            Emoji(id = 53, name = "Roller Coaster", code = 0x1F3A2),
            Emoji(id = 54, name = "Locomotive", code = 0x1F682),
            Emoji(id = 55, name = "Railway Car", code = 0x1F683),
            Emoji(id = 56, name = "High-Speed Train", code = 0x1F684),
            Emoji(id = 57, name = "Bullet Train", code = 0x1F685),
            Emoji(id = 58, name = "Train", code = 0x1F686),
            Emoji(id = 59, name = "Metro", code = 0x1F687),
            Emoji(id = 60, name = "Light Rail", code = 0x1F688),
            Emoji(id = 61, name = "Station", code = 0x1F689),
            Emoji(id = 62, name = "Tram", code = 0x1F68A),
            Emoji(id = 63, name = "Monorail", code = 0x1F69D),
            Emoji(id = 64, name = "Mountain Railway", code = 0x1F69E),
            Emoji(id = 65, name = "Tram Car", code = 0x1F68B),
            Emoji(id = 66, name = "Bus", code = 0x1F68C),
            Emoji(id = 67, name = "Oncoming Bus", code = 0x1F68D),
            Emoji(id = 68, name = "Trolleybus", code = 0x1F68E),
            Emoji(id = 69, name = "Minibus", code = 0x1F690),
            Emoji(id = 70, name = "Ambulance", code = 0x1F691),
            Emoji(id = 71, name = "Fire Engine", code = 0x1F692),
            Emoji(id = 72, name = "Police Car", code = 0x1F693),
            Emoji(id = 73, name = "Oncoming Police Car", code = 0x1F694),
            Emoji(id = 74, name = "Taxi", code = 0x1F695),
            Emoji(id = 75, name = "Oncoming Taxi", code = 0x1F696),
            Emoji(id = 76, name = "Automobile", code = 0x1F697),
            Emoji(id = 77, name = "Oncoming Automobile", code = 0x1F698),
            Emoji(id = 78, name = "Delivery Truck", code = 0x1F69A),
            Emoji(id = 79, name = "Articulated Lorry", code = 0x1F69B),
            Emoji(id = 80, name = "Tractor", code = 0x1F69C),
            Emoji(id = 81, name = "Racing Car", code = 0x1F3CE),
            Emoji(id = 82, name = "Motorcycle", code = 0x1F3CD),
            Emoji(id = 83, name = "Motor Scooter", code = 0x1F6F5),
            Emoji(id = 84, name = "Auto Rickshaw", code = 0x1F6FA),
            Emoji(id = 85, name = "Bicycle", code = 0x1F6B2),
            Emoji(id = 86, name = "Kick Scooter", code = 0x1F6F4),
            Emoji(id = 87, name = "Bus Stop", code = 0x1F68F),
            Emoji(id = 88, name = "Railway Track", code = 0x1F6E4),
            Emoji(id = 89, name = "Fuel Pump", code = 0x26FD),
            Emoji(id = 90, name = "Police Car Light", code = 0x1F6A8),
            Emoji(id = 91, name = "Horizontal Traffic Light", code = 0x1F6A5),
            Emoji(id = 92, name = "Vertical Traffic Light", code = 0x1F6A6),
            Emoji(id = 93, name = "Construction", code = 0x1F6A7),
            Emoji(id = 94, name = "Anchor", code = 0x2693),
            Emoji(id = 95, name = "Sailboat", code = 0x26F5),
            Emoji(id = 96, name = "Speedboat", code = 0x1F6A4),
            Emoji(id = 97, name = "Passenger Ship", code = 0x1F6F3),
            Emoji(id = 98, name = "Ferry", code = 0x26F4),
            Emoji(id = 99, name = "Motor Boat", code = 0x1F6E5),
            Emoji(id = 100, name = "Ship", code = 0x1F6A2),
            Emoji(id = 101, name = "Airplane", code = 0x2708),
            Emoji(id = 102, name = "Small Airplane", code = 0x1F6E9),
            Emoji(id = 103, name = "Airplane Departure", code = 0x1F6EB),
            Emoji(id = 104, name = "Airplane Arrival", code = 0x1F6EC),
            Emoji(id = 105, name = "Parachute", code = 0x1FA82),
            Emoji(id = 106, name = "Seat", code = 0x1F4BA),
            Emoji(id = 107, name = "Helicopter", code = 0x1F681),
            Emoji(id = 108, name = "Suspension Railway", code = 0x1F69F),
            Emoji(id = 109, name = "Mountain Cableway", code = 0x1F6A0),
            Emoji(id = 110, name = "Aerial Tramway", code = 0x1F6A1),
            Emoji(id = 111, name = "Satellite", code = 0x1F6F0),
            Emoji(id = 112, name = "Rocket", code = 0x1F680),
            Emoji(id = 113, name = "Flying Saucer", code = 0x1F6F8),
            Emoji(id = 114, name = "Ringed Planet", code = 0x1FA90),
            Emoji(id = 115, name = "Shooting Star", code = 0x1F320),
            Emoji(id = 116, name = "Milky Way", code = 0x1F30C),
            Emoji(id = 117, name = "Umbrella on Ground", code = 0x26F1),
            Emoji(id = 118, name = "Fireworks", code = 0x1F386),
            Emoji(id = 119, name = "Sparkler", code = 0x1F387),
            Emoji(id = 120, name = "Moon Viewing Ceremony", code = 0x1F391),
            Emoji(id = 121, name = "Yen Banknote", code = 0x1F4B4),
            Emoji(id = 122, name = "Dollar Banknote", code = 0x1F4B5),
            Emoji(id = 123, name = "Euro Banknote", code = 0x1F4B6),
            Emoji(id = 124, name = "Pound Banknote", code = 0x1F4B7),
            Emoji(id = 125, name = "Moai", code = 0x1F5FF),
            Emoji(id = 126, name = "Passport Control", code = 0x1F6C2),
            Emoji(id = 127, name = "Customs", code = 0x1F6C3),
            Emoji(id = 128, name = "Baggage Claim", code = 0x1F6C4),
            Emoji(id = 129, name = "Left Luggage", code = 0x1F6C5)
        )
    }
}